### ISSUE TITLE
Flink memory estimation

### ISSUE THREAD

**Issue by fschueler** [stratosphere/incubator-systemml#29] opened 2016-05-09 15:52 UTC
For operator and broadcast selection we need to estimate/compute different memory characteristics for flink. Since there is now nice API way of doing this we are left with:
- Include the paramters into the SystemML config or use defaults if not specified
- Use the REST API of Flink to access the parameters when available as described [here](http://apache-flink-mailing-list-archive.1008284.n3.nabble.com/Get-TaskManger-Memory-Configuration-from-ExecutionEnvironment-td11537.html)

Right now we're using very conservative magic numbers that are based on Flink's default.

**Comment by akunft** [comment] 2016-05-13 09:51
In 0fdb1e0f2211f65ad8c7b509386a8e8b624e1b34, the issue is addressed by using the estimators provided by Flink. The solution still is not perfect, as we rely on the default fraction of memory assigned to Flink, but provides save estimates even in the case of lazy allocation in Flink (which is the default).

If Flink provides access to the configuration values in the future (apart from the REST API), we should change the current implementation. For now, I think it is ok, as we should rely on the user to set reasonable values in their Flink setup.

**Closed as completed** 2016-05-13 09:54 UTC
